apiVersion: v1
stringData: 
  CELERY_BROKER_URL: ${CELERY_BROKER_URL}
kind: Secret
metadata:
  name: celery-broker-url
  namespace: celery
type: Opaque

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: celery
  name: celery
  namespace: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
      - envFrom:
          - secretRef:
              name: celery-broker-url
          - secretRef:
              name: celery-secrets 
        image: geekzone/backend:${TAG}
        name: celery 
        command: ["sh", "-c", "celery -A web worker -l INFO"]
        resources:
          limits:
            memory: "200Mi"
            cpu: 50m
          requests:
            memory: "50Mi"
            cpu: 30m
