#!/bin/sh -e

# Launch k8s cluster in Azure
cd azure/terraform-azure/
terraform init
terraform apply -auto-approve

# Create resources in the k8s cluster
cd ../k8s/
az aks get-credentials --resource-group geekzone --name GeekZoneCluster --admin
kubectl apply -f namespaces.yaml
envsubst < sealed-secrets/master-key-secret.yaml | sponge sealed-secrets/master-key-secret.yaml
kubectl apply -f sealed-secrets/master-key-secret.yaml
kubectl apply -f sealed-secrets/controller.yaml
kubectl apply -f sealed-secrets/sealed-secrets.yaml
kubectl apply -f ingress-nginx/
sleep 30
kubectl apply -f external-dns/
kubectl apply -f cert-manager/cert-manager.yaml
sleep 120
kubectl apply -f cert-manager/clusterissuer.yaml
kubectl apply -f cert-manager/wildcard-cert.yaml
sleep 30
kubectl apply -f rabbitmq/cluster-operator.yaml
sleep 30
kubectl apply -f rabbitmq/rabbitmq-cluster.yaml
sleep 30
kubectl apply -f rabbitmq/ingress-rabbitmq-mgmt.yaml
export CELERY_BROKER_URL="amqp://$(kubectl -n rabbitmq-system get secret geek-zone-cluster-default-user -o jsonpath='{.data.username}' | base64 --decode):$(kubectl -n rabbitmq-system get secret geek-zone-cluster-default-user -o jsonpath='{.data.password}' | base64 --decode)@$(kubectl -n rabbitmq-system get service geek-zone-cluster -o jsonpath='{.spec.clusterIP}') | base64"
kubectl -n celery get secrets celery-secrets -o yaml > celery/celery-secrets.yaml
sed -i "s/"JENFTEVSWV9CUk9LRVJfVVJM/$CELERY_BROKER_URL/g" celery/celery-secrets.yaml
kubectl apply -f celery/
kubectl apply -f postgres/
sleep 30
kubectl -n prod get secrets prod-secrets -o yaml > prod/prod-secrets.yaml
sed -i "s/"JENFTEVSWV9CUk9LRVJfVVJM/$CELERY_BROKER_URL/g" prod/prod-secrets.yaml
kubectl apply -f prod/
