apiVersion: v1
stringData:
#  CELERY_BROKER_URL: YW1xcDovL2xDSWNDTlZ1YW5tR0VhaVNXRF9UTkpyeVNYMUl5b05KOmhRR241ZGdrSWxMcFFXa2czOXJQbFRyMmxVOUhUYjdJQDE3Mi4yMC4xMzcuMjU0
   CELERY_BROKER_URL: "amqp://KDjFmIfpOVWSecF2f06EG9AAkgFfG7QE:j_q6yz66h2Vi0fZp5yoleEA-_lNz6QY1@172.20.172.254"
kind: Secret
metadata:
  name: celery-secrets
  namespace: celery
  resourceVersion: "5457335"
type: Opaque
