apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-rabbitmq-mgmt
  namespace: rabbitmq-system
spec:
  rules: 
    - host: rabbitmq.geek.zone
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: geek-zone-cluster
                port: 
                  number: 15672
  ingressClassName: nginx