version: 2.1
orbs:
  terraform: circleci/terraform@2.1.0  

executors:
  terraform-executor:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD    

aliases:
  - &show-current-branch-name
    run:
      name: Show current branch
      command: echo ${CIRCLE_BRANCH}

      
jobs:
  terraform-init-validate-plan-apply:
    executor: terraform-executor
    steps:
      - checkout
      - *show-current-branch-name
      
      - run:
          name: Create .terraformrc file locally
          command: >-
            echo "credentials \"app.terraform.io\" {token =
            \"$TERRAFORM_TOKEN\"}" > $HOME/.terraformrc

      - run:
          name: Install dependencies
          command: |
            sudo cp terraform /usr/local/bin
            sudo apt-get update
            sudo apt install gettext-base moreutils -y

      - run:
          name: Fill out template variables in yaml files
          command: |
            export PR_NUMBER=$(echo "pr${CIRCLE_PULL_REQUEST##*/}")
            envsubst < kubernetes.tf | sponge kubernetes.tf

      - run:                  
          name: Terraform Validate & Format
          command: |
            terraform init
            terraform validate

      - run:                  
          name: Terraform Plan & Apply
          command: |            
            terraform plan
            terraform apply --auto-approve

  terraform-destroy:
    executor: terraform-executor
    steps:
      - checkout
      - *show-current-branch-name
      - run:
          command: >-
            echo "credentials \"app.terraform.io\" {token =
            \"$TERRAFORM_TOKEN\"}" > $HOME/.terraformrc
          name: Create .terraformrc file locally
      - run:
          name: Install dependencies
          command: |
                  sudo cp terraform /usr/local/bin
                  sudo apt-get update
                  sudo apt install gettext-base moreutils -y
      - run:
          name: Fill out template variables in yaml files
          command: |
            export RES_NAME=${PR_NUMBER}-${CIRCLE_PROJECT_REPONAME}
            export PR_NUMBER=$(echo "pr${CIRCLE_PULL_REQUEST##*/}")
            envsubst < kubernetes.tf | sponge kubernetes.tf

      - run:
          name: Terraform Destroy
          command: |          
            # run a loop till the time crosses 3 hours and let the job continue to destroy the namesapce. slack message.
            currTime=$(date +%s)
            eAdd=$((60))
            endTime=$((currTime+eAdd))
            while [ $currTime -le $endTime]
            do
              currTime=$(date +%s)
            done
            echo "Continue to destroy-Hurray"
            # terraform init
            # terraform destroy --auto-approve  -target kubernetes_namespace.example.id
            #  terraform destroy --auto-approve

workflows:
  deploy_test_infra:
    jobs:      
      - terraform-init-validate-plan-apply:
          filters:
            branches:
              only:
                - test-infra
                - test_prod_infra
      # - hold:
      #     type: approval
      #     requires:
      #       - terraform-init-validate-plan-apply
      - terraform-destroy:
          requires:
            # - hold
            - terraform-init-validate-plan-apply
          filters:
            branches:
              only:
                - test-infra
                - test_prod_infra

