version: 2.1
orbs:
  terraform: circleci/terraform@3.0.1

executors:
  terraform-executor:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD 

# Set parameter here
# main_infra_build - always run for the main build
parameters:
  deploy_infra_aws:
    type: boolean
    default: false
  deploy_infra_azure:
    type: boolean
    default: false
  main_infra_build:
    type: boolean
    default: true

aliases:
  - &show-current-branch-name
    run:
      name: Show current branch
      command: echo ${CIRCLE_BRANCH}
  - &install-dependencies
    run:
      name: Install dependencies
      command: |
        sudo curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get install terraform -y
        sudo apt install gettext-base moreutils -y
        sudo apt install openssl -y
  - &install-dependencies2
    run:
      name: Install dependencies2
      command: |
            sudo apt-get update
            sudo apt install gettext-base moreutils
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

jobs:
  terraform-cycle:
    executor: terraform/default
    steps:
      - checkout
      - run:
          name: Create .terraformrc file locally
          command: >-
            echo "credentials \"app.terraform.io\" {token =
            \"$TERRAFORM_TOKEN\"}" > $HOME/.terraformrc
      - run:
          name: Terraform cycle
          command: |
            cd aws/terraform-aws
            terraform init -upgrade
            terraform validate
            terraform plan
            cd ../../azure/terraform-azure
            terraform init -upgrade
            terraform validate
            terraform plan
    working_directory: ~/src

  build-publish:
    docker:
      - image: 'cimg/base:stable'
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7    
      - run:
          name: Build geekzone/infra image 
          command: |
            docker build -t geekzone/infra .          
      - deploy:
          name: Push geekzone/infra image to Docker Hub
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push geekzone/infra

  init-switcher-job: 
    executor: terraform-executor
    steps:      
      - checkout
      - *show-current-branch-name
      - *install-dependencies
      - *install-dependencies2
      - run:
          name: Create .terraformrc file locally
          command: >-
            echo "credentials \"app.terraform.io\" {token =
            \"$TERRAFORM_TOKEN\"}" > $HOME/.terraformrc
      - run:
          name: Terraform Validate & Format
          command: |
            cd ./terraform/
            terraform init -upgrade
            terraform fmt
            terraform validate
      - run:
          name: Terraform Plan & Apply
          command: |
            cd ./terraform/
            terraform plan
            terraform apply -auto-approve

  deploy_infra_aws_job:
    executor: terraform-executor
    steps:      
      - checkout
      - *show-current-branch-name
      - *install-dependencies
      - *install-dependencies2
      - run:
          name: Create .terraformrc file locally
          command: >-
            echo " run the AWS infra"
            cd aws/terraform-aws
            terraform init -upgrade
            terraform validate
            terraform plan

  deploy_infra_azure_job:
    executor: terraform-executor
    steps:      
      - checkout
      - *show-current-branch-name
      - *install-dependencies
      - *install-dependencies2
      - run:
          name: Create .terraformrc file locally
          command: >-
            echo " run the AZURE infra"
            cd azure/terraform-azure
            terraform init -upgrade
            terraform validate
            terraform plan 
 
workflows:
  main-infra:
    when: << pipeline.parameters.main_infra_build >>  
    jobs:
      - terraform-cycle:
          filters:
            branches:
              ignore: 
              - /junk-.*/
      - build-publish:
          requires:
          - terraform-cycle
          filters:
            branches:
              ignore: 
              - /junk-.*/
      - init-switcher-job:
          requires:
          - build-publish
          filters:
              branches:
                only: /main*/
          context:
            - org-global
  deploy_switcher_infra_aws:
    when: << pipeline.parameters.deploy_infra_aws >>  
    jobs:
      - deploy_infra_aws_job:
          filters:
              branches:
                ignore: 
                - /junk-.*/
                - /doc-.*/
          context:
            - org-global
  deploy_infra_azure:
    when: << pipeline.parameters.deploy_infra_azure >>  
    jobs:
      - deploy_infra_azure_job:
          filters:
              branches:
                ignore: 
                - /junk-.*/
                - /doc-.*/
          context:
            - org-global
