version: 2.1
jobs:
  terraform-cycle:
    docker:
      - image: cimg/base:current
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
      - run:
          name: Create .terraformrc file locally
          command: |
            echo "credentials \"app.terraform.io\" {token =
            \"$TERRAFORM_TOKEN\"}" > $HOME/.terraformrc
      - run:
          name: Install Terraform binary
          command: |
            sudo su
            curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
            apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" -y
            apt-get update && apt-get install terraform=1.4.2 -y
      - run:
          name: terraform format
          command: |
            cd azure/terraform-azure
            terraform fmt -recursive
      - run:
          name: terraform init
          command: |
            cd /azure/terraform-azure
            terraform init 
      - run:
          name: terraform validate
          command: |
            cd /azure/terraform-azure
            terraform validate
      - run:
          name: terraform plan
          command: |
            cd /azure/terraform-azure
            terraform plan
      # - terraform/apply:
      #     path: .
      # - terraform/destroy:
      #     path: .
    # working_directory: ~/src

  build-publish:
    docker:
      - image: 'cimg/base:stable'
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7    
      - run:
          name: Build geekzone/infra image 
          command: |
            docker build -t geekzone/infra .          
      - deploy:
          name: Push geekzone/infra image to Docker Hub
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push geekzone/infra


workflows:
  main-infra:
    jobs:
      - terraform-cycle:
          filters:
            branches:
              ignore: 
              - /^doc-.*/
      - build-publish:
          requires:
          - terraform-cycle
          filters:
            branches:
              ignore: 
              - /^doc-.*/


