version: 2.1
orbs:
  terraform: circleci/terraform@3.0.1
jobs:
  terraform-cycle:
    executor: terraform/default
    steps:
      - checkout
      - run:
          name: Create .terraformrc file locally
          command: >-
            echo "credentials \"app.terraform.io\" {token =
            \"$TERRAFORM_TOKEN\"}" > $HOME/.terraformrc
      - run: 
          name: Terraform cycle
          command: |
            cd aws/terraform-aws
            terraform fmt 
            terraform validate
            terraform init 
            terraform plan 
      #       terraform apply -auto-approve
      # - run:
      #     name: Destroy infrastructure
      #       terraform destroy -auto-approve
      #     command: terraform destroy -auto-approve
             
    working_directory: ~/src
workflows:
  terraform-cycle:
    jobs:
      - terraform-cycle:
          filters:
            branches:
              ignore: 
              - /junk-.*/
              - /doc-.*/
