version: 2.1
orbs:
  terraform: circleci/terraform@3.0.1
jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - run:
          command: >-
            echo "credentials \"app.terraform.io\" {token =
            \"$TERRAFORM_TOKEN\"}" > $HOME/.terraformrc
          name: Create .terraformrc file locally
      # - terraform/install:
      #     arch: amd64
      #     os: linux
      #     terraform_version: 1.0.5
      - terraform/fmt:
          path: .
      - terraform/validate:
          path: .
      - terraform/init:
          backend: true
          path: aws/terraform-aws
      - terraform/plan:
          path: aws/terraform-aws
      - terraform/apply:
          path: aws/terraform-aws
      - terraform/destroy:
          path: aws/terraform-aws
    working_directory: ~/src
workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle:
          filters:
            branches:
              ignore: 
              - /junk-.*/
              - /doc-.*/
