version: 2.1
orbs:
  terraform: circleci/terraform@3.0.1
jobs:
  terraform-cycle:
    executor: terraform/default
    steps:
      - checkout
      - run:
          command: >-
            echo "credentials \"app.terraform.io\" {token =
            \"$TERRAFORM_TOKEN\"}" > $HOME/.terraformrc
          name: Create .terraformrc file locally
      # - terraform/install:
      #     arch: amd64
      #     os: linux
      #     terraform_version: 1.0.5
      - run: 
          name: Terraform cycle
          command: |
            cd aws/terraform-aws
            terraform fmt 
            terraform init 
            terraform plan 
            terraform apply -auto-approve
            terraform destroy -auto-approve
             
    working_directory: ~/src
workflows:
  terraform-cycle:
    jobs:
      - terraform-cycle:
          filters:
            branches:
              ignore: 
              - /junk-.*/
              - /doc-.*/
