apiVersion: v1
stringData: 
  CELERY_BROKER_URL: ${CELERY_BROKER_URL}
kind: Secret
metadata:
  name: celery-broker-url
  namespace: prod
type: Opaque

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gz-web
  namespace: prod
  labels:
    app: gz-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gz-web
  template:
    metadata:
      labels:
        app: gz-web
    spec:
      initContainers:
      - name: wait-for-migration
        image: geekzone/backend:0.1.${CIRCLE_WORKFLOW_ID}
        command: ['python3', 'manage.py', 'migrate']
        envFrom:
          - secretRef:
              name: prod-secrets
      - name: wait-for-database
        image: geekzone/backend:0.1.${CIRCLE_WORKFLOW_ID}
        command: ['python3', 'manage.py', 'wait_for_database']
        envFrom:
          - secretRef:
              name: prod-secrets
      containers:
      - name: django-backend
        image: geekzone/backend:0.1.${CIRCLE_WORKFLOW_ID}
        envFrom:
          - secretRef:
              name: celery-broker-url
          - secretRef:
              name: prod-secrets
        resources:
          limits:
            memory: "100Mi"
            cpu: 50m
          requests:
            memory: "50Mi"
            cpu: 30m
      - name: frontend-proxy
        image: geekzone/frontend:0.1.${CIRCLE_WORKFLOW_ID}
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          limits:
            memory: "50Mi"
            cpu: 50m
          requests:
            memory: "30Mi"
            cpu: 30m

---
apiVersion: v1
kind: Service
metadata:
  name: gz-web-service
  namespace: prod
  annotations:
    external-dns.alpha.kubernetes.io/hostname: join.geek.zone
#    external-dns.alpha.kubernetes.io/ttl: "120" #optional
spec:
  type: ClusterIP
  selector:
    app: gz-web
  ports:
  - port: 80
    targetPort: 8080
