apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gz-web
  namespace: web
spec:
  maxReplicas: 6
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gz-web
  targetCPUUtilizationPercentage: 50 
