apiVersion: v1
kind: Secret
metadata:
  name: web-secrets 
  namespace: web 
type: Opaque
stringData: 
  DEBUG: "0"
  ALLOWED_HOSTS: "test.geek.zone"
  STRIPE_SECRET_KEY: "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"
  STRIPE_PUBLIC_KEY: "pk_live_51H10VbJh8KDe9GPFv9pQcSWSybLk6nSC0wKDpp7sGPWq0TNI3DDNnYpLHs7aPEUImYgPBYXbhk3W5tTqZEiEaIQb00kKXK2QI4"
  SAND_PRICE_ID: "price_1HDveaJh8KDe9GPFiya9gKoZ"
  DONATION_PRODUCT_ID: "prod_HnmOmrwV7zDBfw"
  GMAIL_APP_PASSWORD: "qkwxtoicalslhsnl"
  DATABASE_HOST: "geekzone.cqedj3rbwgfi.eu-west-2.rds.amazonaws.com"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "geekzone"
  DATABASE_USER: "postgres"       
  DATABASE_PASSWORD: "Q#4fkZ9$9SPvgVB27q3U"
  CELERY_BROKER_URL: "amqp://KDjFmIfpOVWSecF2f06EG9AAkgFfG7QE:j_q6yz66h2Vi0fZp5yoleEA-_lNz6QY1@172.20.172.254"
  #CELERY_BACKEND: "amqp://lCIcCNVuanmGEaiSWD_TNJrySX1IyoNJ:hQGn5dgkIlLpQWkg39rPlTr2lU9HTb7I@172.20.137.254"
