#!/bin/sh -e

# Create resources in the k8s cluster
cd aws/k8s/
kubectl apply -f namespaces.yaml
envsubst < sealed-secrets/master-key-secret.yaml | sponge sealed-secrets/master-key-secret.yaml
kubectl apply -f sealed-secrets/master-key-secret.yaml
kubectl apply -f sealed-secrets/controller.yaml
kubectl apply -f sealed-secrets/sealed-secrets.yaml
kubectl apply -f aws-storage-class.yaml
kubectl apply -f keda-2.5.0.yaml
kubectl apply -f external-dns/
kubectl apply -f ingress-nginx/
kubectl apply -f rabbitmq/cluster-operator.yaml
sleep 30
kubectl apply -f rabbitmq/rabbitmq-cluster.yaml
sleep 30
kubectl apply -f rabbitmq/ingress-rabbitmq-mgmt.yaml
export CELERY_BROKER_URL=$(echo -n "amqp://$(kubectl -n rabbitmq-system get secret geek-zone-cluster-default-user -o jsonpath='{.data.username}' | base64 --decode):$(kubectl -n rabbitmq-system get secret geek-zone-cluster-default-user -o jsonpath='{.data.password}' | base64 --decode)@$(kubectl -n rabbitmq-system get service geek-zone-cluster -o jsonpath='{.spec.clusterIP}')")
envsubst < celery/celery-deploy.yaml | sponge celery/celery-deploy.yaml
kubectl apply -f celery/
export PR_NUMBER=$(echo "pr${CIRCLE_PULL_REQUEST##*/}")
envsubst < test-environment/deploy-test.yaml | sponge test-environment/deploy-test.yaml
kubectl -n ${PR_NUMBER}-${CIRCLE_PROJECT_REPONAME} apply -f test-environment/
kubectl -n ${PR_NUMBER}-${CIRCLE_PROJECT_REPONAME} rollout status deployment test-gz-web

