#!/bin/sh -e

# Delete load-balancer associated to ingress controller
cd aws/k8s/
kubectl delete -f ingress-nginx/ingress-controller-tls-termination.yaml

# Destroy k8s cluster in AWS 
cd ../terraform-aws
terraform init
terraform destroy -auto-approve


