apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      name: postgres
  template:
    metadata:
      labels:
       name: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          envFrom:
          - secretRef:
              name: postgres-secrets
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql
          resources:
            limits:
              memory: "50Mi"
              cpu: 50m
            requests:
              memory: "30Mi"
              cpu: 30m
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    name: postgres
