apiVersion: apps/v1
kind: Deployment
metadata:
  name: gz-web
  labels:
    app: gz-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gz-web
  template:
    metadata:
      labels:
        app: gz-web
    spec:
      containers:
      - name: django-backend
        image: giuntalio/django-app:1.0 
        env:
          - name: DEBUG
            value: "on"
          - name: ALLOWED_HOSTS
            value: test.geek.zone 
          - name: DATABASE_URL
            value: sqlite:/db.sqlite
        resources:
          limits:
            memory: "100Mi"
            cpu: 50m
          requests:
            memory: "50Mi"
            cpu: 30m
      - name: nginx-proxy
        image: 098281131088.dkr.ecr.eu-west-2.amazonaws.com/gz-nginx-proxy:1.0
        resources:
          limits:
            memory: "50Mi"
            cpu: 30m
          requests:
            memory: "30Mi"
            cpu: 20m

---
apiVersion: v1
kind: Service
metadata:
  name: gz-web-service
spec:
  type: ClusterIP 
  selector:
    app: gz-web
  ports:
  - port: 80
    targetPort: 80
