apiVersion: batch/v1
kind: CronJob
metadata:
  name: destroy-azure-infra 
  namespace: infra
spec:
  schedule: "0 */4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: destroy-azure-infra
            image: geekzone/infra
            imagePullPolicy: IfNotPresent
            command: ['destroy-azure-infra']
            volumeMounts:
            - name: terraform
              mountPath: "/home/infra-admin"
              readOnly: true
          volumes:
          - name: terraform
            secret:
              secretName: terraform-token
              optional: false
          restartPolicy: OnFailure
    
  